
outdir: output 

stat_interval: 10
total_connections: 100   # total connections per interval
same_ns_ratio: 30
batch_size: 5


workloads: 
  namespaces: 3
  deployments: 2
  replicaset: 1
  total_labels: 1000
